language: scala
branches:
  only:
    - master
script:
  - cp project/CrossSettings.template project/CrossSettings.scala
  - sbt robotJVM/test robotJVM/assembly robotNative/compile robotJVM/scalafixTest
  - ./scalafmt --test
